apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: msusers
  name: msusers
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: msusers
  template:
    metadata:
      labels:
        deployment: msusers
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: msusers
        - name: MYSQL_PASSWORD
          value: admin
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_USER
          value: admin
        image: mariadb
        name: msusers
        ports:
        - containerPort: 3306
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: msusers-volume-1
        - mountPath: /etc/mysql/conf.d/
          name: mariadb-config
        - mountPath: /docker-entrypoint-initdb.d/
          name: country-users-table-schemas
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: msusers-volume-1
      - configMap:
          name: mariadb-config
        name: mariadb-config
      - configMap:
          name: country-users-table-schemas
        name: country-users-table-schemas

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: msusers
  name: msusers
spec:
  ports:
  - name: 3306-tcp
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    deployment: msusers

