apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus-ds
spec:
  instanceSelector:
    matchLabels:
      app: grafana
      dashboards: grafana
  datasource:
    name: prometheus-DS
    type: prometheus
    url: 'http://prometheus-operated.prometheus.svc.cluster.local:9090'
    access: proxy
    editable: true
    basicAuth: false
    isDefault: true
    jsonData:
      timeInterval: 5s
      tlsSkipVerify: true
  plugins:
    - name: grafana-clock-panel
      version: 2.1.8
