apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    name: Grafana-DS
    type: prometheus
    url: 'https://prometheus-operated.prometheus.svc.cluster.local:909'
    access: proxy
    editable: true
    basicAuth: false
    isDefault: true
    jsonData:
      timeInterval: 5s
      tlsSkipVerify: true
  plugins:
    - name: grafana-clock-panel
      version: 2.1.8
