apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    name: Thanos-DS
    type: prometheus
    url: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9091'
    access: proxy
    editable: true
    basicAuth: false
    isDefault: true
    jsonData:
      timeInterval: 5s
      tlsSkipVerify: true
      httpHeaderName1: Authorization
    secureJsonData:
      httpHeaderValue1: "Bearer ${GRAFANA-ACCESS-TOKEN}"
  plugins:
    - name: grafana-clock-panel
      version: 2.1.7
