apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app: msusers
#  annotations:
#    note: generated

configMapGenerator:
- name: mariadb-config
  files:
    - primary.cnf=./primary.cnf


