apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: amq-streams-kafka-connect
  namespace: openshift-gitops
spec:
  destination:
    namespace: amqstreams
    server: "https://kubernetes.default.svc"
  # Target ArgoCD project where this application will be created
  project: playground
  source:
    repoURL: "https://github.com/ryanezil/cluster-bootstrapping"
    path: platform/amq-streams-kafka-connect
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
