apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amq-streams-operator
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-operators
    server: "https://kubernetes.default.svc"
  # Target ArgoCD project where this application will be created
  project: playground
  source:
    repoURL: "https://github.com/ryanezil/cluster-bootstrapping"
    path: platform/amq-streams-operator
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
