apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: service-registry-operator
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-operators
    server: "https://kubernetes.default.svc"
  # Target ArgoCD project where this application will be created
  project: playground
  source:
    repoURL: "https://github.com/ryanezil/cluster-bootstrapping"
    path: platform/service-registry-operator
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
