{
 "title": "AMQ Broker Control Panel",
 "description": "Red Hat AMQ Broker monitoring",
 "tags": [ "AMQ Broker" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(artemis_connection_count{namespace=~\".*\",namespace!~\".*-bld|.*monitoring|.*meta|.*dev.*|.*tst.*\"}, namespace)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(artemis_connection_count{namespace=~\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Global Max Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (broker) ( artemis_address_memory_usage_percentage{pod=\"$instance\", namespace=\"$namespace\"} )",
     "legendFormat": "{{ broker }}"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(jvm_memory_used_bytes{area=~\"heap\", pod=~\"$instance\", namespace=~\"$namespace\"}[1m]))*100/sum(avg_over_time(jvm_memory_max_bytes{area=~\"heap\", pod=~\"$instance\", namespace=~\"$namespace\"}[5m]))"
    }
   ]
  },
  {
   "title": "Total Message Count",
   "type": "stat",
   "description": "Total message count in all queues in the selected instances",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (broker)(artemis_message_count{pod=~'$instance',  namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Total Addresses Count",
   "type": "stat",
   "description": "Total message count in all queues in the selected instances",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (artemis_unrouted_message_count{pod=~'$instance',  namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Average Disk usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (broker) ( artemis_disk_store_usage{pod=~\"$instance\", namespace=~\"$namespace\"} )",
     "legendFormat": "{{broker}}"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kube_pod_start_time{namespace=~\"$namespace\",pod=~\"$instance\"})*1000"
    }
   ]
  },
  {
   "title": "Up Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - avg(kube_pod_start_time{namespace=~\"$namespace\",pod=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Restart Count / 7days",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, increase(kube_pod_container_status_restarts_total{namespace=~\"$namespace\",pod=~\"$instance\"}[7d]))",
     "legendFormat": "Restart Count"
    }
   ]
  },
  {
   "title": "Msg OUT Throughput",
   "type": "stat",
   "description": "Throughput for the selected instances",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (broker) ( (rate(artemis_messages_acknowledged{pod=~\"$instance\", namespace=\"$namespace\"}[1m])))",
     "legendFormat": "OUT"
    }
   ]
  },
  {
   "title": "Msg IN Throughput",
   "type": "stat",
   "description": "Throughput for the selected instances",
   "gridPos": { "h": 6, "w": 4, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (broker) ( (rate(artemis_messages_added{pod=~\"$instance\", namespace=\"$namespace\"}[1m])))",
     "legendFormat": "IN"
    }
   ]
  },
  {
   "title": "Operator Version",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "kube_pod_labels{namespace=~\"$namespace\", pod=~\"$instance\", label_rht_subcomp =~ \"broker-amq\"} unless kube_pod_labels{namespace=~\"$namespace\", pod=~\"$instance\", label_rht_coom =~ \"AMQ\"}"
    }
   ]
  },
  {
   "title": "Started",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{pod=~\"$instance\",  namespace=~\"$namespace\"}",
     "legendFormat": "Instance: {{pod}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (broker) ( artemis_connection_count{pod=~\"$instance\",  namespace=~\"$namespace\"} )"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (broker) ( artemis_session_count{pod=~\"$instance\",  namespace=~\"$namespace\"} )"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "CPU Usage (millicores)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{resource=\"cpu\", pod=~\"$instance\", namespace=\"$namespace\"}",
     "legendFormat": "Container limit [{{pod}}]"
    },
    {
     "expr": "kube_pod_container_resource_requests{resource=\"cpu\", pod=~\"$instance\", namespace=\"$namespace\"}",
     "legendFormat": "Container request [{{pod}}]"
    },
    {
     "expr": "pod:container_cpu_usage:sum{pod=~\"$instance\", namespace=\"$namespace\"}",
     "legendFormat": "Usage [{{pod}}]"
    }
   ]
  },
  {
   "title": "Memory Info",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{unit=~\"byte\",namespace=~\"$namespace\",pod=~\"$instance\"}) by (pod)",
     "legendFormat": "POD Mem Request [{{pod}}]"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{unit=~\"byte\",namespace=~\"$namespace\",pod=~\"$instance\"}) by (pod)",
     "legendFormat": "POD Mem Limit [{{pod}}]"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{area=~\"heap\", pod=~\"$instance\", namespace=~\"$namespace\"}) by (pod)",
     "legendFormat": "Heap Max [{{pod}}]"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{area=~\"heap\", pod=~\"$instance\", namespace=~\"$namespace\"}) by (pod)",
     "legendFormat": "Heap Usage [{{pod}}]"
    },
    {
     "expr": "sum (artemis_address_memory_usage{pod=~\"$instance\",  namespace=~\"$namespace\"}) by (pod)",
     "legendFormat": "Global Max Usage [{{pod}}]"
    }
   ]
  },
  { "title": "Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Message Throughput",
   "type": "graph",
   "description": "Aggregation of the selected instances",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (broker) (rate(artemis_messages_added{pod=~\"$instance\", namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "Producing"
    },
    {
     "expr": "sum by (broker) (rate(artemis_messages_acknowledged{pod=~\"$instance\", namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "Consuming"
    }
   ]
  },
  {
   "title": "Connections and Consumers by instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (artemis_connection_count{pod=~\"$instance\",  namespace=~\"$namespace\"})",
     "legendFormat": "Total Connection Count [{{pod}}]"
    },
    {
     "expr": "sum by (pod) (artemis_session_count{pod=~\"$instance\",  namespace=~\"$namespace\"})",
     "legendFormat": "Total Session Count [{{pod}}]"
    },
    {
     "expr": "sum by (pod) (artemis_consumer_count{pod=~\"$instance\",  namespace=~\"$namespace\"})",
     "legendFormat": "Total Consumers connected to [{{pod}}]"
    }
   ]
  },
  {
   "title": "Consumers - TOP 20 queues",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (address) ( topk (20, artemis_consumer_count{pod=~\"$instance\",  namespace=~\"$namespace\"} ) )",
     "legendFormat": "Consumers connected to [{{address}}]"
    }
   ]
  },
  {
   "title": "Message Count - TOP 20 queues",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (queue) ( topk (20, artemis_message_count{pod=~\"$instance\",  namespace=~\"$namespace\", address!~\"\\\\$.*|activemq\\\\.notifications\"} ) )",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Persistent Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (broker) (artemis_persistent_size{pod=~\"$instance\", namespace=~\"$namespace\"})",
     "legendFormat": "Total {{broker}}"
    },
    {
     "expr": "sum by (queue) ( topk (20, artemis_persistent_size{pod=~\"$instance\", namespace=~\"$namespace\", address!~\"\\\\$.*|activemq\\\\.notifications\"} ) )",
     "legendFormat": "Queue: {{queue}}"
    }
   ]
  },
  {
   "title": "Messages Production Rate - TOP 20 queues",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (queue) ( topk (20, rate(artemis_messages_added{pod=~\"$instance\", namespace=~\"$namespace\", address!~\"\\\\$.*|activemq\\\\.notifications\"}[1m]) ) )",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Messages consumption Rate - TOP 20 queues",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (queue) ( topk (20, rate(artemis_messages_acknowledged{pod=~\"$instance\", namespace=~\"$namespace\", address!~\"\\\\$.*|activemq\\\\.notifications\"}[1m]) ) )",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Messages Expired",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (queue) ( topk (20, rate(artemis_messages_expired{pod=~\"$instance\", namespace=~\"$namespace\"}[1m]) ) )",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "artemis_disk_store_usage{pod=~\"$instance\",  namespace=~\"$namespace\"}",
     "legendFormat": "Instance [{{pod}}]"
    }
   ]
  },
  {
   "title": "Paging",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (broker) ( artemis_number_of_pages{pod=~\"$instance\", namespace=~\"$namespace\"} )",
     "legendFormat": "{{broker}}"
    },
    {
     "expr": "sum by (address) ( topk (20, artemis_number_of_pages{pod=~\"$instance\", namespace=~\"$namespace\"} ) )",
     "legendFormat": "{{address}}"
    }
   ]
  }
 ]
}