apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app: msusers
#  annotations:
#    note: generated

configMapGenerator:
- name: country-users-table-schemas
  files:
    - france-ddl.sql=./france-ddl.sql
    - portugal-ddl.sql=./portugal-ddl.sql


