---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: my-connect-single-node-cluster
  annotations:
    description: "AMQ Streams - Kafka Connect cluster"
  # Annotation 'use-connector-resources' configures this KafkaConnect
  # to use KafkaConnector resources to avoid
  # needing to call the Connect REST API directly
    strimzi.io/use-connector-resources: "true"
spec:
  version: 3.7.0
  build:
    output:
      # Use type 'docker' to push built image into a container registry like Docker Hub or Quay.io
      type: imagestream
      image: my-kafka-connect-image:0.0.1
    plugins:
    - name: debezium-connector-mysql
      artifacts:
      - type: zip
        url: https://maven.repository.redhat.com/ga/io/debezium/debezium-connector-mysql/2.5.4.Final-redhat-00001/debezium-connector-mysql-2.5.4.Final-redhat-00001-plugin.zip
        sha512sum: eac4956994316c76a9eefe480fa7711f3b3b0c6440a25afe8d0d753abf06161476fbab39f4af8a81a2f594ffa17e47778edd3ed8451e6009c26740b7d073acd1
      - type: zip
        url: https://maven.repository.redhat.com/ga/io/apicurio/apicurio-registry-distro-connect-converter/2.5.9.Final-redhat-00001/apicurio-registry-distro-connect-converter-2.5.9.Final-redhat-00001.zip
        sha512sum: 81f57991791f87ba8d9c9c2bc8392bc1cf927a14838a33fcdf1fb04fb0a203cc5370f9d43b95069c1c9c90ce776999dfa945abca601b2b6d2a0b44fe0beff329

  replicas: 1
  bootstrapServers: single-node-cluster-kafka-bootstrap:9092
#  authentication:
#    type: scram-sha-512
#    username: superuser
#    passwordSecret:
#      secretName: superuser
#      password: password
#  tls:
#    trustedCertificates:
#      - secretName: single-node-cluster-cluster-ca-cert
#        certificate: ca.crt
  config:
    group.id: my-kconnect-cluster-groupid
    # Default value is TRUE when topic autocreation is not set:
    topic.creation.enable: "true"
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1

  logging:
#    type: external
#    valueFrom:
#      configMapKeyRef:
#        name: logging-config-cm
#        key: logging.properties
    type: inline
    loggers:
      log4j.rootLogger: INFO
      log4j.logger.io.debezium.connector.mongodb: TRACE
  resources:
#    requests:
#      cpu: 500m
#      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 2Gi
  readinessProbe:
    initialDelaySeconds: 180
    timeoutSeconds: 30
  livenessProbe:
    initialDelaySeconds: 180
    timeoutSeconds: 30
